version: "3"

services:
  www:
    build: .
    env_file:
      - .env
    volumes:
      - .:/var/www
    ports:
      - 3000:3000
    links:
      - mysql
      - redis
  mysql:
    image: 'bitnami/mariadb:10.5'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=nordev-marketeer
      - MARIADB_DATABASE=nordev-marketeer
      - MARIADB_PASSWORD=nordev-marketeer
  redis:
    image: 'redis:6'
